# Placement-b

In [1]:
import numpy as np
import pandas as pd 

In [2]:
dataset = pd.read_csv(r"C:\Users\saiku\Downloads\Placement_Data_Full_Class.csv")

In [3]:
dataset.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [4]:
dataset.isnull().any()

sl_no             False
gender            False
ssc_p             False
ssc_b             False
hsc_p             False
hsc_b             False
hsc_s             False
degree_p          False
degree_t          False
workex            False
etest_p           False
specialisation    False
mba_p             False
status            False
salary             True
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["status"]=le.fit_transform(dataset["status"])

In [6]:
x = dataset.iloc[:,1:13].values
y = dataset.iloc[:,13].values

In [7]:
x

array([['M', 67.0, 'Others', ..., 55.0, 'Mkt&HR', 58.8],
       ['M', 79.33, 'Central', ..., 86.5, 'Mkt&Fin', 66.28],
       ['M', 65.0, 'Central', ..., 75.0, 'Mkt&Fin', 57.8],
       ...,
       ['M', 67.0, 'Others', ..., 59.0, 'Mkt&Fin', 69.72],
       ['F', 74.0, 'Others', ..., 70.0, 'Mkt&HR', 60.23],
       ['M', 62.0, 'Central', ..., 89.0, 'Mkt&HR', 60.22]], dtype=object)

In [8]:
dataset.head(3)

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   

    degree_t workex  etest_p specialisation  mba_p  status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80       1  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28       1  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80       1  250000.0

In [9]:
dataset["gender"].unique()

array(['M', 'F'], dtype=object)

In [10]:
dataset["ssc_b"].unique()

array(['Others', 'Central'], dtype=object)

In [11]:
dataset["workex"].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
dataset["hsc_s"].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [13]:
dataset["hsc_b"].unique()

array(['Others', 'Central'], dtype=object)

In [14]:
dataset["degree_t"].unique()

array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

In [15]:

dataset["specialisation"].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["gender"] = le.fit_transform(dataset["gender"])
dataset["ssc_b"] = le.fit_transform(dataset["ssc_b"])
dataset["hsc_b"] = le.fit_transform(dataset["hsc_b"])
dataset["hsc_s"] = le.fit_transform(dataset["hsc_s"])
dataset["degree_t"] = le.fit_transform(dataset["degree_t"])
dataset["workex"] = le.fit_transform(dataset["workex"])
dataset["specialisation"] = le.fit_transform(dataset["specialisation"])


In [17]:
dataset

sl_no  gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  \
0        1       1  67.00      1  91.00      1      1     58.00         2   
1        2       1  79.33      0  78.33      1      2     77.48         2   
2        3       1  65.00      0  68.00      0      0     64.00         0   
3        4       1  56.00      0  52.00      0      2     52.00         2   
4        5       1  85.80      0  73.60      0      1     73.30         0   
5        6       1  55.00      1  49.80      1      2     67.25         2   
6        7       0  46.00      1  49.20      1      1     79.00         0   
7        8       1  82.00      0  64.00      0      2     66.00         2   
8        9       1  73.00      0  79.00      0      1     72.00         0   
9       10       1  58.00      0  70.00      0      1     61.00         0   
10      11       1  58.00      0  61.00      0      1     60.00         0   
11      12       1  69.60      0  68.40      0      1     78.30         0   
12      13       0  47.00      0  55.00      1      2     65.00         0   
13      14       0  77.00      0  87.00      0      1     59.00         0   
14      15       1  62.00      0  47.00      0      1     50.00         0   
15      16       0  65.00      0  75.00      0      1     69.00         0   
16      17       1  63.00      0  66.20      0      1     65.60         0   
17      18       0  55.00      0  67.00      0      1     64.00         0   
18      19       0  63.00      0  66.00      0      1     64.00         0   
19      20       1  60.00      1  67.00      1      0     70.00         0   
20      21       1  62.00      1  65.00      1      1     66.00         0   
21      22       0  79.00      1  76.00      1      1     85.00         0   
22      23       0  69.80      1  60.80      1      2     72.23         2   
23      24       0  77.40      1  60.00      1      2     64.74         2   
24      25       1  76.50      1  97.70      1      2     78.86         2   
25      26       0  52.58      1  54.60      0      1     50.20         0   
26      27       1  71.00      1  79.00      1      1     66.00         0   
27      28       1  63.00      1  67.00      1      1     66.00         0   
28      29       1  76.76      1  76.50      1      1     67.50         0   
29      30       1  62.00      0  67.00      0      1     58.00         0   
..     ...     ...    ...    ...    ...    ...    ...       ...       ...   
185    186       0  88.00      0  72.00      0      2     78.00         1   
186    187       0  52.00      0  64.00      0      1     61.00         0   
187    188       1  78.50      0  65.50      0      2     67.00         2   
188    189       1  61.80      1  47.00      1      1     54.38         0   
189    190       0  54.00      0  77.60      1      1     69.20         0   
190    191       0  64.00      1  70.20      0      1     61.00         0   
191    192       1  67.00      1  61.00      0      2     72.00         0   
192    193       1  65.20      0  61.40      0      1     64.80         0   
193    194       0  60.00      0  63.00      0      0     56.00         1   
194    195       1  52.00      1  55.00      1      1     56.30         0   
195    196       1  66.00      0  76.00      0      1     72.00         0   
196    197       1  72.00      1  63.00      1      2     77.50         2   
197    198       0  83.96      1  53.00      1      2     91.00         2   
198    199       0  67.00      0  70.00      0      1     65.00         1   
199    200       1  69.00      1  65.00      1      1     57.00         0   
200    201       1  69.00      1  60.00      1      1     65.00         0   
201    202       1  54.20      0  63.00      1      2     58.00         0   
202    203       1  70.00      0  63.00      0      2     66.00         2   
203    204       1  55.68      1  61.33      1      1     56.87         0   
204    205       0  74.00      1  73.00      1      1     73.00         0   
2

In [18]:
x = dataset.iloc[:,1:13]
y = dataset.iloc[:,13]

In [19]:
x

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  workex  \
0         1  67.00      1  91.00      1      1     58.00         2       0   
1         1  79.33      0  78.33      1      2     77.48         2       1   
2         1  65.00      0  68.00      0      0     64.00         0       0   
3         1  56.00      0  52.00      0      2     52.00         2       0   
4         1  85.80      0  73.60      0      1     73.30         0       0   
5         1  55.00      1  49.80      1      2     67.25         2       1   
6         0  46.00      1  49.20      1      1     79.00         0       0   
7         1  82.00      0  64.00      0      2     66.00         2       1   
8         1  73.00      0  79.00      0      1     72.00         0       0   
9         1  58.00      0  70.00      0      1     61.00         0       0   
10        1  58.00      0  61.00      0      1     60.00         0       1   
11        1  69.60      0  68.40      0      1     78.30         0       1   
12        0  47.00      0  55.00      1      2     65.00         0       0   
13        0  77.00      0  87.00      0      1     59.00         0       0   
14        1  62.00      0  47.00      0      1     50.00         0       0   
15        0  65.00      0  75.00      0      1     69.00         0       1   
16        1  63.00      0  66.20      0      1     65.60         0       1   
17        0  55.00      0  67.00      0      1     64.00         0       0   
18        0  63.00      0  66.00      0      1     64.00         0       0   
19        1  60.00      1  67.00      1      0     70.00         0       1   
20        1  62.00      1  65.00      1      1     66.00         0       0   
21        0  79.00      1  76.00      1      1     85.00         0       0   
22        0  69.80      1  60.80      1      2     72.23         2       0   
23        0  77.40      1  60.00      1      2     64.74         2       1   
24        1  76.50      1  97.70      1      2     78.86         2       0   
25        0  52.58      1  54.60      0      1     50.20         0       1   
26        1  71.00      1  79.00      1      1     66.00         0       1   
27        1  63.00      1  67.00      1      1     66.00         0       0   
28        1  76.76      1  76.50      1      1     67.50         0       1   
29        1  62.00      0  67.00      0      1     58.00         0       0   
..      ...    ...    ...    ...    ...    ...       ...       ...     ...   
185       0  88.00      0  72.00      0      2     78.00         1       0   
186       0  52.00      0  64.00      0      1     61.00         0       0   
187       1  78.50      0  65.50      0      2     67.00         2       1   
188       1  61.80      1  47.00      1      1     54.38         0       0   
189       0  54.00      0  77.60      1      1     69.20         0       0   
190       0  64.00      1  70.20      0      1     61.00         0       0   
191       1  67.00      1  61.00      0      2     72.00         0       0   
192       1  65.20      0  61.40      0      1     64.80         0       1   
193       0  60.00      0  63.00      0      0     56.00         1       1   
194       1  52.00      1  55.00      1      1     56.30         0       0   
195       1  66.00      0  76.00      0      1     72.00         0       1   
196       1  72.00      1  63.00      1      2     77.50         2       1   
197       0  83.96      1  53.00      1      2     91.00         2       0   
198       0  67.00      0  70.00      0      1     65.00         1       0   
199       1  69.00      1  65.00      1      1     57.00         0       0   
200       1  69.00      1  60.00      1      1     65.00         0       0   
201       1  54.20      0  63.00      1      2     58.00         0       0   
202       1  70.00      0  63.00      0      2     66.00         2       0   
203       1  55.68      1  61.33      1      1     56.87         0       0   
204       0  74.00      1  

In [20]:
y

0      1
1      1
2      1
3      0
4      1
5      0
6      0
7      1
8      1
9      0
10     1
11     1
12     0
13     1
14     0
15     1
16     1
17     0
18     0
19     1
20     1
21     1
22     1
23     1
24     1
25     0
26     1
27     1
28     1
29     0
      ..
185    1
186    0
187    1
188    0
189    0
190    0
191    1
192    1
193    1
194    0
195    1
196    1
197    1
198    0
199    1
200    1
201    0
202    1
203    1
204    1
205    1
206    0
207    1
208    0
209    1
210    1
211    1
212    1
213    1
214    0
Name: status, Length: 215, dtype: int32

In [21]:
x = dataset.iloc[:,1:13].values
y = dataset.iloc[:,13].values

In [22]:
x

array([[ 1.  , 67.  ,  1.  , ..., 55.  ,  1.  , 58.8 ],
       [ 1.  , 79.33,  0.  , ..., 86.5 ,  0.  , 66.28],
       [ 1.  , 65.  ,  0.  , ..., 75.  ,  0.  , 57.8 ],
       ...,
       [ 1.  , 67.  ,  1.  , ..., 59.  ,  0.  , 69.72],
       [ 0.  , 74.  ,  1.  , ..., 70.  ,  1.  , 60.23],
       [ 1.  , 62.  ,  0.  , ..., 89.  ,  1.  , 60.22]])

In [23]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [24]:
x.shape

(215, 12)

In [25]:
y.shape

(215,)

In [26]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(),[0,2,4,5,7,8,10])],remainder = "passthrough") 
x = ct.fit_transform(x)

C:\Users\saiku\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [27]:
x

array([[ 0.  ,  1.  ,  0.  , ..., 58.  , 55.  , 58.8 ],
       [ 0.  ,  1.  ,  1.  , ..., 77.48, 86.5 , 66.28],
       [ 0.  ,  1.  ,  1.  , ..., 64.  , 75.  , 57.8 ],
       ...,
       [ 0.  ,  1.  ,  0.  , ..., 73.  , 59.  , 69.72],
       [ 1.  ,  0.  ,  0.  , ..., 58.  , 70.  , 60.23],
       [ 0.  ,  1.  ,  1.  , ..., 53.  , 89.  , 60.22]])

In [28]:

x.shape

(215, 21)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)


In [30]:
x_train.shape

(172, 21)

In [31]:
x_test.shape

(43, 21)

In [32]:
from sklearn.preprocessing import StandardScaler 
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [33]:
x_train

array([[-0.73192505,  0.73192505,  0.90029235, ..., -0.08327934,
        -0.91848631,  0.05194371],
       [ 1.3662601 , -1.3662601 ,  0.90029235, ...,  0.36837381,
        -1.24217438,  0.57709192],
       [ 1.3662601 , -1.3662601 ,  0.90029235, ...,  0.40822555,
         0.58224933,  1.48972813],
       ...,
       [-0.73192505,  0.73192505, -1.1107503 , ...,  0.89973045,
         0.55282314,  0.81842217],
       [-0.73192505,  0.73192505,  0.90029235, ..., -1.22569612,
         0.40569219, -1.30596381],
       [-0.73192505,  0.73192505, -1.1107503 , ..., -1.35853529,
         0.84708503, -1.63056998]])

In [34]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 


In [35]:
ann=Sequential()

In [36]:
ann.add(Dense(21, kernel_initializer = "random_uniform",  activation = "relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [37]:
ann.add(Dense(42, kernel_initializer = "random_uniform",  activation = "relu"))

In [38]:
ann.add(Dense(1, kernel_initializer = "random_uniform",  activation = "sigmoid"))

In [39]:
ann.compile("adam","binary_crossentropy",metrics = ["accuracy"])

In [40]:
ann.fit(x_train,y_train,batch_size = 32,epochs = 15)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/15
172/172 [==============================] - 0s 2ms/sample - loss: 0.6923 - acc: 0.6570
Epoch 2/15
172/172 [==============================] - 0s 81us/sample - loss: 0.6892 - acc: 0.7035
Epoch 3/15
172/172 [==============================] - 0s 99us/sample - loss: 0.6855 - acc: 0.7035
Epoch 4/15
172/172 [==============================] - 0s 99us/sample - loss: 0.6797 - acc: 0.7035
Epoch 5/15
172/172 [==============================] - 0s 81us/sample - loss: 0.6717 - acc: 0.7035
Epoch 6/15
172/172 [==============================] - 0s 64us/sample - loss: 0.6595 - acc: 0.7151
Epoch 7/15
172/172 [==============================] - 0s 70us/sample - loss: 0.6427 - acc: 0.7384
Epoch 8/15
172/172 [==============================] - 0s 75us/sample - loss: 0.6180 - acc: 0.7791
Epoch 9/15
172/172 [==============================] - 0s 75us/sample - loss: 0.5885 - acc: 0.8081
Epoch 10/15
172/172 [====

In [41]:
ypred = ann.predict(x_test)

In [42]:
ypred

array([[0.4486685 ],
       [0.58363676],
       [0.8711721 ],
       [0.41148874],
       [0.9757434 ],
       [0.6072681 ],
       [0.8880526 ],
       [0.5953115 ],
       [0.8529813 ],
       [0.9887779 ],
       [0.5418339 ],
       [0.8571529 ],
       [0.885774  ],
       [0.4570529 ],
       [0.7318289 ],
       [0.3922742 ],
       [0.9558406 ],
       [0.40070054],
       [0.91653734],
       [0.7770617 ],
       [0.32146114],
       [0.4659256 ],
       [0.7300957 ],
       [0.5605266 ],
       [0.3925254 ],
       [0.52687633],
       [0.660643  ],
       [0.8278382 ],
       [0.71236396],
       [0.92625165],
       [0.9327363 ],
       [0.59093237],
       [0.90880746],
       [0.57136095],
       [0.477239  ],
       [0.9791389 ],
       [0.97837245],
       [0.81397104],
       [0.95917   ],
       [0.83182144],
       [0.41444087],
       [0.39994782],
       [0.8513633 ]], dtype=float32)

In [43]:
ypred = ypred>0.5

In [44]:
ypred

array([[False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True]])

In [45]:
y_test

array([0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1])

In [46]:
dataset.head()

sl_no  gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  \
0      1       1  67.00      1  91.00      1      1     58.00         2   
1      2       1  79.33      0  78.33      1      2     77.48         2   
2      3       1  65.00      0  68.00      0      0     64.00         0   
3      4       1  56.00      0  52.00      0      2     52.00         2   
4      5       1  85.80      0  73.60      0      1     73.30         0   

   workex  etest_p  specialisation  mba_p  status    salary  
0       0     55.0               1  58.80       1  270000.0  
1       1     86.5               0  66.28       1  200000.0  
2       0     75.0               0  57.80       1  250000.0  
3       0     66.0               1  59.43       0       NaN  
4       0     96.8               0  55.50       1  425000.0

In [47]:
yp = ann.predict(sc.transform(ct.transform([[1,8.6,0,93.5,1,1,55.9,2,0,54.0,0,56.7]])))

In [48]:
yp

array([[0.34463525]], dtype=float32)

In [49]:
yp>0.5

array([[False]])

# Loanstatus-b

In [52]:
dataset = pd.read_csv(r"C:\Users\saiku\Downloads\Loanstatus.csv")

In [53]:
dataset

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes         3+      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
12   LP001028    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
18   LP001038    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
20   LP001043    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
24   LP001052    Male     Yes          1      Graduate           NaN   
25   LP001066    Male     Yes          0      Graduate           Yes   
26   LP001068    Male     Yes          0      Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   
29   LP001087  Female      No          2      Graduate           NaN   
..        ...     ...     ...        ...           ...           ...   
584  LP002911    Male     Yes          1      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
588  LP002925     NaN      No          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
591  LP002931    Male     Yes          2      Graduate           Yes   
592  LP002933     NaN      No         3+      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
599  LP002948    Male     Yes          2      Graduate            No   
600  LP002949  Female      No         3+      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
602  LP002953    Male     Yes         3+      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not 

In [54]:
dataset.isnull().any()

Loan_ID              False
Gender                True
Married               True
Dependents            True
Education            False
Self_Employed         True
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount            True
Loan_Amount_Term      True
Credit_History        True
Property_Area        False
Loan_Status          False
dtype: bool

In [55]:
dataset=dataset.replace(to_replace="3+",value=3)

In [56]:
dataset["Dependents"].unique()

array(['0', '1', '2', 3, nan], dtype=object)

In [57]:

dataset

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
6    LP001013    Male     Yes          0  Not Graduate            No   
7    LP001014    Male     Yes          3      Graduate            No   
8    LP001018    Male     Yes          2      Graduate            No   
9    LP001020    Male     Yes          1      Graduate            No   
10   LP001024    Male     Yes          2      Graduate            No   
11   LP001027    Male     Yes          2      Graduate           NaN   
12   LP001028    Male     Yes          2      Graduate            No   
13   LP001029    Male      No          0      Graduate            No   
14   LP001030    Male     Yes          2      Graduate            No   
15   LP001032    Male      No          0      Graduate            No   
16   LP001034    Male      No          1  Not Graduate            No   
17   LP001036  Female      No          0      Graduate            No   
18   LP001038    Male     Yes          0  Not Graduate            No   
19   LP001041    Male     Yes          0      Graduate           NaN   
20   LP001043    Male     Yes          0  Not Graduate            No   
21   LP001046    Male     Yes          1      Graduate            No   
22   LP001047    Male     Yes          0  Not Graduate            No   
23   LP001050     NaN     Yes          2  Not Graduate            No   
24   LP001052    Male     Yes          1      Graduate           NaN   
25   LP001066    Male     Yes          0      Graduate           Yes   
26   LP001068    Male     Yes          0      Graduate            No   
27   LP001073    Male     Yes          2  Not Graduate            No   
28   LP001086    Male      No          0  Not Graduate            No   
29   LP001087  Female      No          2      Graduate           NaN   
..        ...     ...     ...        ...           ...           ...   
584  LP002911    Male     Yes          1      Graduate            No   
585  LP002912    Male     Yes          1      Graduate            No   
586  LP002916    Male     Yes          0      Graduate            No   
587  LP002917  Female      No          0  Not Graduate            No   
588  LP002925     NaN      No          0      Graduate            No   
589  LP002926    Male     Yes          2      Graduate           Yes   
590  LP002928    Male     Yes          0      Graduate            No   
591  LP002931    Male     Yes          2      Graduate           Yes   
592  LP002933     NaN      No          3      Graduate           Yes   
593  LP002936    Male     Yes          0      Graduate            No   
594  LP002938    Male     Yes          0      Graduate           Yes   
595  LP002940    Male      No          0  Not Graduate            No   
596  LP002941    Male     Yes          2  Not Graduate           Yes   
597  LP002943    Male      No        NaN      Graduate            No   
598  LP002945    Male     Yes          0      Graduate           Yes   
599  LP002948    Male     Yes          2      Graduate            No   
600  LP002949  Female      No          3      Graduate           NaN   
601  LP002950    Male     Yes          0  Not Graduate           NaN   
602  LP002953    Male     Yes          3      Graduate            No   
603  LP002958    Male      No          0      Graduate            No   
604  LP002959  Female     Yes          1      Graduate            No   
605  LP002960    Male     Yes          0  Not Graduate            No   
606  LP002961    Male     Yes          1      Graduate            No   
607  LP002964    Male     Yes          2  Not 

In [58]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)
dataset["Married"].fillna(dataset["Married"].mode()[0],inplace=True)
dataset["Dependents"].fillna(dataset["Dependents"].mode()[0],inplace=True)
dataset["Self_Employed"].fillna(dataset["Self_Employed"].mode()[0],inplace=True)
dataset["LoanAmount"].fillna(dataset["LoanAmount"].mean(),inplace=True)
dataset["Loan_Amount_Term"].fillna(dataset["Loan_Amount_Term"].mean(),inplace=True)
dataset["Credit_History"].fillna(dataset["Credit_History"].mean(),inplace=True)

In [59]:
dataset.isnull().any()

Loan_ID              False
Gender               False
Married              False
Dependents           False
Education            False
Self_Employed        False
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount           False
Loan_Amount_Term     False
Credit_History       False
Property_Area        False
Loan_Status          False
dtype: bool

In [60]:
dataset["Gender"].mode()[0]

'Male'

In [61]:
dataset["Married"].mode()[0]

'Yes'

In [62]:
dataset["Dependents"].mode()[0]

'0'

In [63]:
dataset["Self_Employed"].mode()[0]

'No'

In [64]:
dataset["LoanAmount"].mean()

146.41216216216213

In [65]:
dataset["Loan_Amount_Term"].mean()

342.0

In [66]:
dataset["Credit_History"].mean()

0.8421985815602844

In [67]:
dataset.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [68]:
dataset["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [69]:
dataset["Married"].unique()

array(['No', 'Yes'], dtype=object)

In [70]:
dataset["Education"].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [71]:
dataset["Self_Employed"].unique()

array(['No', 'Yes'], dtype=object)

In [72]:
dataset["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [73]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Gender"] = le.fit_transform(dataset["Gender"])
dataset["Married"] = le.fit_transform(dataset["Married"])
dataset["Education"] = le.fit_transform(dataset["Education"])
dataset["Self_Employed"] = le.fit_transform(dataset["Self_Employed"])
dataset["Property_Area"] = le.fit_transform(dataset["Property_Area"])
dataset["Loan_ID"] = le.fit_transform(dataset["Loan_ID"])

In [74]:
dataset.head()

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0        0       1        0          0          0              0   
1        1       1        1          1          0              0   
2        2       1        1          0          0              1   
3        3       1        1          0          1              0   
4        4       1        0          0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Property_Area Loan_Status  
0             1.0              2           Y  
1             1.0              0           N  
2             1.0              2           Y  
3             1.0              2           Y  
4             1.0              2           Y

In [75]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Loan_Status"]=le.fit_transform(dataset["Loan_Status"])

In [76]:
x = dataset.iloc[:,0:12]
y = dataset.iloc[:,12]

In [77]:
x

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0          0       1        0          0          0              0   
1          1       1        1          1          0              0   
2          2       1        1          0          0              1   
3          3       1        1          0          1              0   
4          4       1        0          0          0              0   
5          5       1        1          2          0              1   
6          6       1        1          0          1              0   
7          7       1        1          3          0              0   
8          8       1        1          2          0              0   
9          9       1        1          1          0              0   
10        10       1        1          2          0              0   
11        11       1        1          2          0              0   
12        12       1        1          2          0              0   
13        13       1        0          0          0              0   
14        14       1        1          2          0              0   
15        15       1        0          0          0              0   
16        16       1        0          1          1              0   
17        17       0        0          0          0              0   
18        18       1        1          0          1              0   
19        19       1        1          0          0              0   
20        20       1        1          0          1              0   
21        21       1        1          1          0              0   
22        22       1        1          0          1              0   
23        23       1        1          2          1              0   
24        24       1        1          1          0              0   
25        25       1        1          0          0              1   
26        26       1        1          0          0              0   
27        27       1        1          2          1              0   
28        28       1        0          0          1              0   
29        29       0        0          2          0              0   
..       ...     ...      ...        ...        ...            ...   
584      584       1        1          1          0              0   
585      585       1        1          1          0              0   
586      586       1        1          0          0              0   
587      587       0        0          0          1              0   
588      588       1        0          0          0              0   
589      589       1        1          2          0              1   
590      590       1        1          0          0              0   
591      591       1        1          2          0              1   
592      592       1        0          3          0              1   
593      593       1        1          0          0              0   
594      594       1        1          0          0              1   
595      595       1        0          0          1              0   
596      596       1        1          2          1              1   
597      597       1        0          0          0              0   
598      598       1        1          0          0              1   
599      599       1        1          2          0              0   
600      600       0        0          3          0              0   
601      601       1        1          0          1              0   
602      602       1        1          3          0              0   
603      603       1        0          0          0              0   
604      604       0        1          1          0              0   
605      605       1        1          0          1              0   
606      606       1        1          1          0              0   
607      607       1        1          2          1              0   
608      608       1        1          0          0              0   
609      609   

In [78]:

y

0      1
1      0
2      1
3      1
4      1
5      1
6      1
7      0
8      1
9      0
10     1
11     1
12     1
13     0
14     1
15     1
16     1
17     0
18     0
19     1
20     0
21     1
22     0
23     0
24     0
25     1
26     1
27     1
28     0
29     1
      ..
584    0
585    0
586    1
587    1
588    1
589    0
590    1
591    0
592    1
593    1
594    1
595    1
596    0
597    0
598    1
599    1
600    0
601    1
602    1
603    1
604    1
605    0
606    1
607    1
608    1
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int32

In [79]:
x = dataset.iloc[:,0:12].values
y = dataset.iloc[:,12].values

In [80]:
x

array([[0, 1, 0, ..., 360.0, 1.0, 2],
       [1, 1, 1, ..., 360.0, 1.0, 0],
       [2, 1, 1, ..., 360.0, 1.0, 2],
       ...,
       [611, 1, 1, ..., 360.0, 1.0, 2],
       [612, 1, 1, ..., 360.0, 1.0, 2],
       [613, 0, 0, ..., 360.0, 0.0, 1]], dtype=object)

In [81]:
y

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

In [82]:
x.shape

(614, 12)

In [83]:
y.shape

(614,)

In [84]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(),[1,2,4,5,11])],remainder = "passthrough") 
x = ct.fit_transform(x)

C:\Users\saiku\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [85]:
x

array([[0.0, 1.0, 1.0, ..., 146.41216216216216, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 128.0, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 66.0, 360.0, 1.0],
       ...,
       [0.0, 1.0, 0.0, ..., 253.0, 360.0, 1.0],
       [0.0, 1.0, 0.0, ..., 187.0, 360.0, 1.0],
       [1.0, 0.0, 1.0, ..., 133.0, 360.0, 0.0]], dtype=object)

In [86]:
x.shape

(614, 18)

In [87]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)


In [88]:
x_train.shape

(491, 18)

In [89]:
x_test.shape

(123, 18)

In [90]:
from sklearn.preprocessing import StandardScaler 

In [91]:
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [92]:
x_train

array([[-0.47374983,  0.47374983, -0.71143163, ..., -0.18814516,
         0.27644707,  0.45859914],
       [-0.47374983,  0.47374983,  1.40561644, ...,  0.56269516,
         0.27644707,  0.01148007],
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.01977985,
         0.27644707, -2.37482957],
       ...,
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.60890072,
         0.27644707,  0.45859914],
       [-0.47374983,  0.47374983, -0.71143163, ...,  0.14684514,
         0.27644707,  0.45859914],
       [ 2.11081869, -2.11081869, -0.71143163, ...,  0.40097571,
         0.27644707,  0.45859914]])

In [93]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 


In [94]:
ann = Sequential()

In [95]:
ann.add(Dense(18, kernel_initializer = "random_uniform",  activation = "relu"))

In [96]:

ann.add(Dense(36, kernel_initializer = "random_uniform",  activation = "relu"))

In [97]:
ann.add(Dense(1, kernel_initializer = "random_uniform",  activation = "sigmoid"))

In [98]:
ann.compile("adam","binary_crossentropy",metrics = ["accuracy"])

In [99]:
ann.fit(x_train,y_train,batch_size = 32,epochs = 25)

Epoch 1/25
491/491 [==============================] - 0s 538us/sample - loss: 0.6904 - acc: 0.6640
Epoch 2/25
491/491 [==============================] - 0s 71us/sample - loss: 0.6822 - acc: 0.6762
Epoch 3/25
491/491 [==============================] - 0s 73us/sample - loss: 0.6650 - acc: 0.6762
Epoch 4/25
491/491 [==============================] - 0s 99us/sample - loss: 0.6338 - acc: 0.6762
Epoch 5/25
491/491 [==============================] - 0s 65us/sample - loss: 0.5885 - acc: 0.7067
Epoch 6/25
491/491 [==============================] - 0s 65us/sample - loss: 0.5468 - acc: 0.7576
Epoch 7/25
491/491 [==============================] - 0s 53us/sample - loss: 0.5178 - acc: 0.7923
Epoch 8/25
491/491 [==============================] - 0s 55us/sample - loss: 0.4975 - acc: 0.8065
Epoch 9/25
491/491 [==============================] - 0s 69us/sample - loss: 0.4822 - acc: 0.8065
Epoch 10/25
491/491 [==============================] - 0s 69us/sample - loss: 0.4690 - acc: 0.8065
Epoch 11/25
491/49

In [100]:
ypred = ann.predict(x_test)

In [101]:
ypred

array([[0.8364914 ],
       [0.90515137],
       [0.738441  ],
       [0.8662813 ],
       [0.9269351 ],
       [0.07880539],
       [0.9253949 ],
       [0.68529963],
       [0.03441733],
       [0.93080604],
       [0.91724205],
       [0.93594146],
       [0.6798135 ],
       [0.8079432 ],
       [0.85641897],
       [0.89364475],
       [0.64605033],
       [0.8115151 ],
       [0.5633255 ],
       [0.0497767 ],
       [0.03607225],
       [0.9251534 ],
       [0.8595934 ],
       [0.79433596],
       [0.60079753],
       [0.8388394 ],
       [0.6890159 ],
       [0.7956055 ],
       [0.03968796],
       [0.05775324],
       [0.753582  ],
       [0.5229819 ],
       [0.9106101 ],
       [0.71373314],
       [0.867132  ],
       [0.06867898],
       [0.8921262 ],
       [0.67566097],
       [0.8919907 ],
       [0.89729404],
       [0.8215891 ],
       [0.04766154],
       [0.96344197],
       [0.72520614],
       [0.87386286],
       [0.4785252 ],
       [0.91899425],
       [0.888

In [102]:
ypred = ypred>0.5

In [103]:
ypred

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [104]:
y_test

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1])

In [105]:
dataset.head(3)

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0        0       1        0          0          0              0   
1        1       1        1          1          0              0   
2        2       1        1          0          0              1   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1

In [106]:
yp = ann.predict(sc.transform(ct.transform([[2,1,0,1,1,0,325,12.7,3986,768.8,1,2]])))

In [107]:
yp

array([[0.930585]], dtype=float32)

In [108]:
yp>0.5

array([[ True]])

# 50startups-c

In [109]:
dataset=pd.read_csv(r"C:\Users\saiku\Downloads\50_startups.csv")

FileNotFoundError: [Errno 2] File b'C:\\Users\\saiku\\Downloads\\50_startups.csv' does not exist: b'C:\\Users\\saiku\\Downloads\\50_startups.csv'

In [110]:
dataset

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0          0       1        0          0          0              0   
1          1       1        1          1          0              0   
2          2       1        1          0          0              1   
3          3       1        1          0          1              0   
4          4       1        0          0          0              0   
5          5       1        1          2          0              1   
6          6       1        1          0          1              0   
7          7       1        1          3          0              0   
8          8       1        1          2          0              0   
9          9       1        1          1          0              0   
10        10       1        1          2          0              0   
11        11       1        1          2          0              0   
12        12       1        1          2          0              0   
13        13       1        0          0          0              0   
14        14       1        1          2          0              0   
15        15       1        0          0          0              0   
16        16       1        0          1          1              0   
17        17       0        0          0          0              0   
18        18       1        1          0          1              0   
19        19       1        1          0          0              0   
20        20       1        1          0          1              0   
21        21       1        1          1          0              0   
22        22       1        1          0          1              0   
23        23       1        1          2          1              0   
24        24       1        1          1          0              0   
25        25       1        1          0          0              1   
26        26       1        1          0          0              0   
27        27       1        1          2          1              0   
28        28       1        0          0          1              0   
29        29       0        0          2          0              0   
..       ...     ...      ...        ...        ...            ...   
584      584       1        1          1          0              0   
585      585       1        1          1          0              0   
586      586       1        1          0          0              0   
587      587       0        0          0          1              0   
588      588       1        0          0          0              0   
589      589       1        1          2          0              1   
590      590       1        1          0          0              0   
591      591       1        1          2          0              1   
592      592       1        0          3          0              1   
593      593       1        1          0          0              0   
594      594       1        1          0          0              1   
595      595       1        0          0          1              0   
596      596       1        1          2          1              1   
597      597       1        0          0          0              0   
598      598       1        1          0          0              1   
599      599       1        1          2          0              0   
600      600       0        0          3          0              0   
601      601       1        1          0          1              0   
602      602       1        1          3          0              0   
603      603       1        0          0          0              0   
604      604       0        1          1          0              0   
605      605       1        1          0          1              0   
606      606       1        1          1          0              0   
607      607       1        1          2          1              0   
608      608       1        1          0          0              0   
609      609   

In [111]:
titles=list(dataset.columns)
titles

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [112]:
titles[3],titles[0]=titles[0],titles[3]
titles

['Dependents',
 'Gender',
 'Married',
 'Loan_ID',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status']

In [113]:
dataset=dataset[titles]
dataset

Dependents  Gender  Married  Loan_ID  Education  Self_Employed  \
0            0       1        0        0          0              0   
1            1       1        1        1          0              0   
2            0       1        1        2          0              1   
3            0       1        1        3          1              0   
4            0       1        0        4          0              0   
5            2       1        1        5          0              1   
6            0       1        1        6          1              0   
7            3       1        1        7          0              0   
8            2       1        1        8          0              0   
9            1       1        1        9          0              0   
10           2       1        1       10          0              0   
11           2       1        1       11          0              0   
12           2       1        1       12          0              0   
13           0       1        0       13          0              0   
14           2       1        1       14          0              0   
15           0       1        0       15          0              0   
16           1       1        0       16          1              0   
17           0       0        0       17          0              0   
18           0       1        1       18          1              0   
19           0       1        1       19          0              0   
20           0       1        1       20          1              0   
21           1       1        1       21          0              0   
22           0       1        1       22          1              0   
23           2       1        1       23          1              0   
24           1       1        1       24          0              0   
25           0       1        1       25          0              1   
26           0       1        1       26          0              0   
27           2       1        1       27          1              0   
28           0       1        0       28          1              0   
29           2       0        0       29          0              0   
..         ...     ...      ...      ...        ...            ...   
584          1       1        1      584          0              0   
585          1       1        1      585          0              0   
586          0       1        1      586          0              0   
587          0       0        0      587          1              0   
588          0       1        0      588          0              0   
589          2       1        1      589          0              1   
590          0       1        1      590          0              0   
591          2       1        1      591          0              1   
592          3       1        0      592          0              1   
593          0       1        1      593          0              0   
594          0       1        1      594          0              1   
595          0       1        0      595          1              0   
596          2       1        1      596          1              1   
597          0       1        0      597          0              0   
598          0       1        1      598          0              1   
599          2       1        1      599          0              0   
600          3       0        0      600          0              0   
601          0       1        1      601          1              0   
602          3       1        1      602          0              0   
603          0       1        0      603          0              0   
604          1       0        1      604          0              0   
605          0       1        1      605          1              0   
606          1       1        1      606          0              0   
607          2       1        1      607          1              0   
608          0       1        1      608          0              0   
609          0

In [114]:
dataset.isnull().any()

Dependents           False
Gender               False
Married              False
Loan_ID              False
Education            False
Self_Employed        False
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount           False
Loan_Amount_Term     False
Credit_History       False
Property_Area        False
Loan_Status          False
dtype: bool

In [115]:
dataset["Administration"].fillna(dataset["Administration"].mean(),inplace=True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(),inplace=True)

KeyError: 'Administration'

In [116]:
dataset.isnull().any()

Dependents           False
Gender               False
Married              False
Loan_ID              False
Education            False
Self_Employed        False
ApplicantIncome      False
CoapplicantIncome    False
LoanAmount           False
Loan_Amount_Term     False
Credit_History       False
Property_Area        False
Loan_Status          False
dtype: bool

In [117]:
dataset

Dependents  Gender  Married  Loan_ID  Education  Self_Employed  \
0            0       1        0        0          0              0   
1            1       1        1        1          0              0   
2            0       1        1        2          0              1   
3            0       1        1        3          1              0   
4            0       1        0        4          0              0   
5            2       1        1        5          0              1   
6            0       1        1        6          1              0   
7            3       1        1        7          0              0   
8            2       1        1        8          0              0   
9            1       1        1        9          0              0   
10           2       1        1       10          0              0   
11           2       1        1       11          0              0   
12           2       1        1       12          0              0   
13           0       1        0       13          0              0   
14           2       1        1       14          0              0   
15           0       1        0       15          0              0   
16           1       1        0       16          1              0   
17           0       0        0       17          0              0   
18           0       1        1       18          1              0   
19           0       1        1       19          0              0   
20           0       1        1       20          1              0   
21           1       1        1       21          0              0   
22           0       1        1       22          1              0   
23           2       1        1       23          1              0   
24           1       1        1       24          0              0   
25           0       1        1       25          0              1   
26           0       1        1       26          0              0   
27           2       1        1       27          1              0   
28           0       1        0       28          1              0   
29           2       0        0       29          0              0   
..         ...     ...      ...      ...        ...            ...   
584          1       1        1      584          0              0   
585          1       1        1      585          0              0   
586          0       1        1      586          0              0   
587          0       0        0      587          1              0   
588          0       1        0      588          0              0   
589          2       1        1      589          0              1   
590          0       1        1      590          0              0   
591          2       1        1      591          0              1   
592          3       1        0      592          0              1   
593          0       1        1      593          0              0   
594          0       1        1      594          0              1   
595          0       1        0      595          1              0   
596          2       1        1      596          1              1   
597          0       1        0      597          0              0   
598          0       1        1      598          0              1   
599          2       1        1      599          0              0   
600          3       0        0      600          0              0   
601          0       1        1      601          1              0   
602          3       1        1      602          0              0   
603          0       1        0      603          0              0   
604          1       0        1      604          0              0   
605          0       1        1      605          1              0   
606          1       1        1      606          0              0   
607          2       1        1      607          1              0   
608          0       1        1      608          0              0   
609          0

In [118]:
dataset['State'].unique()

KeyError: 'State'

In [119]:
x=dataset.iloc[:,1:5].values
y=dataset.iloc[:,0:1].values

In [120]:
y

array([['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['2'],
       ['0'],
       [3],
       ['2'],
       ['1'],
       ['2'],
       ['2'],
       ['2'],
       ['0'],
       ['2'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['2'],
       ['1'],
       ['0'],
       ['0'],
       ['2'],
       ['0'],
       ['2'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       [3],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['2'],
       ['1'],
       ['2'],
       ['0'],
       ['0'],
       ['1'],
       ['2'],
       ['0'],
       [3],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       [3],
       ['0'],
       ['0'],
       ['2'],


In [121]:
y.ndim

2

In [122]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

C:\Users\saiku\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [123]:
y

array([[1.0, 0.0, 0.0, 0.0],
       [0.0, 1.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, 0.0],
       ...,
       [0.0, 1.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, 0.0],
       [1.0, 0.0, 0.0, 0.0]], dtype=object)

In [124]:

y.ndim

2

In [125]:
y.shape

(614, 4)

In [126]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [127]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [128]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [129]:
cat=Sequential()

In [130]:
cat.add(Dense(4,kernel_initializer="random_uniform",activation="relu"))

In [131]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

In [132]:
cat.add(Dense(3,kernel_initializer="random_uniform",activation="softmax"))

In [133]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [134]:
cat.fit(x_train,y_train,batch_size=32,epochs=15)

Epoch 1/15


InvalidArgumentError: logits and labels must be broadcastable: logits_size=[32,3] labels_size=[32,4]
	 [[{{node loss_2/output_1_loss/softmax_cross_entropy_with_logits}}]]

In [ ]:
x_train.shape

In [ ]:
y_train.shape

In [135]:
ypred=cat.predict(x_test)

In [136]:
ypred

array([[0.33331954, 0.33335918, 0.33332127],
       [0.33323467, 0.33344162, 0.33332375],
       [0.33333036, 0.33334893, 0.33332065],
       [0.33333078, 0.33334696, 0.3333223 ],
       [0.33330896, 0.3334039 , 0.3332871 ],
       [0.33330646, 0.33340856, 0.33328497],
       [0.3333304 , 0.33334905, 0.33332062],
       [0.33331975, 0.33335888, 0.33332145],
       [0.33331722, 0.33336118, 0.3333216 ],
       [0.3333307 , 0.33334735, 0.333322  ],
       [0.33327395, 0.33340696, 0.33331916],
       [0.3333306 , 0.33334783, 0.3333216 ],
       [0.33326128, 0.33341587, 0.3333228 ],
       [0.33333194, 0.3333508 , 0.3333172 ],
       [0.333331  , 0.33334562, 0.33332336],
       [0.33333203, 0.3333511 , 0.33331683],
       [0.33333334, 0.33333334, 0.33333334],
       [0.33333334, 0.33333334, 0.33333334],
       [0.33330065, 0.33338803, 0.33331138],
       [0.33332446, 0.33338037, 0.3332952 ],
       [0.33326098, 0.33346272, 0.33327627],
       [0.33333096, 0.3333459 , 0.33332312],
       [0.

In [137]:
ypred[0]

array([0.33331954, 0.33335918, 0.33332127], dtype=float32)

In [138]:
y_test[0]

array([1.0, 0.0, 0.0, 0.0], dtype=object)

In [139]:
ypred[1]

array([0.33323467, 0.33344162, 0.33332375], dtype=float32)

In [140]:
y_test[1]

array([1.0, 0.0, 0.0, 0.0], dtype=object)

In [141]:
dataset.head()

Dependents  Gender  Married  Loan_ID  Education  Self_Employed  \
0          0       1        0        0          0              0   
1          1       1        1        1          0              0   
2          0       1        1        2          0              1   
3          0       1        1        3          1              0   
4          0       1        0        4          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0  146.412162             360.0   
1             4583             1508.0  128.000000             360.0   
2             3000                0.0   66.000000             360.0   
3             2583             2358.0  120.000000             360.0   
4             6000                0.0  141.000000             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1  
3             1.0              2            1  
4             1.0              2            1

In [142]:
cat.predict_classes(sc.transform([[125,345,225,546]]))

array([1], dtype=int64)

# toy dataset-c

In [143]:
dataset=pd.read_csv(r"C:\Users\saiku\Downloads\toy_dataset.csv")

In [144]:
dataset

Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
1            2  Dallas    Male   54   45084.0      No
2            3  Dallas    Male   42   52483.0      No
3            4  Dallas    Male   40   40941.0      No
4            5  Dallas    Male   46   50289.0      No
5            6  Dallas  Female   36   50786.0      No
6            7  Dallas  Female   32   33155.0      No
7            8  Dallas    Male   39   30914.0      No
8            9  Dallas    Male   51   68667.0      No
9           10  Dallas  Female   30   50082.0      No
10          11  Dallas  Female   48   41524.0     Yes
11          12  Dallas    Male   47   54777.0      No
12          13  Dallas    Male   46   62749.0      No
13          14  Dallas  Female   42   50894.0      No
14          15  Dallas  Female   61   38429.0      No
15          16  Dallas    Male   43   34074.0      No
16          17  Dallas    Male   27   50398.0      No
17          18  Dallas    Male   38   46373.0     Yes
18          19  Dallas    Male   47   51137.0      No
19          20  Dallas  Female   35   23688.0      No
20          21  Dallas    Male   57   17378.0      No
21          22  Dallas    Male   33   45919.0      No
22          23  Dallas  Female   33   23001.0      No
23          24  Dallas  Female   27   34292.0     Yes
24          25  Dallas    Male   58   55190.0      No
25          26  Dallas    Male   64   26169.0      No
26          27  Dallas    Male   58   57322.0      No
27          28  Dallas    Male   44   61704.0      No
28          29  Dallas    Male   34   53619.0      No
29          30  Dallas    Male   45   47421.0     Yes
...        ...     ...     ...  ...       ...     ...
149970  149971  Austin  Female   63   99950.0      No
149971  149972  Austin  Female   30   76928.0      No
149972  149973  Austin    Male   46   84395.0      No
149973  149974  Austin  Female   52   77272.0      No
149974  149975  Austin  Female   39   90430.0      No
149975  149976  Austin  Female   51   92132.0      No
149976  149977  Austin    Male   49   91519.0      No
149977  149978  Austin    Male   51  107123.0      No
149978  149979  Austin    Male   58  100949.0      No
149979  149980  Austin    Male   43   86737.0      No
149980  149981  Austin  Female   53   89384.0     Yes
149981  149982  Austin    Male   50   77134.0      No
149982  149983  Austin  Female   47   92157.0      No
149983  149984  Austin  Female   25   92482.0      No
149984  149985  Austin    Male   51   99075.0      No
149985  149986  Austin  Female   25   74947.0      No
149986  149987  Austin  Female   63   80381.0      No
149987  149988  Austin  Female   55   62501.0      No
149988  149989  Austin  Female   26   77823.0      No
149989  149990  Austin    Male   52   83688.0      No
149990  149991  Austin  Female   26   82163.0      No
149991  149992  Austin    Male   51   97510.0      No
149992  149993  Austin    Male   37   88408.0      No
149993  149994  Austin    Male   64   89906.0      No
149994  149995  Austin  Female   37  106097.0      No
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

[150000 rows x 6 columns]

In [145]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Gender"]=le.fit_transform(dataset["Gender"])

In [146]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset["Illness"]=le.fit_transform(dataset["Illness"])

In [147]:
dataset.head()

Number    City  Gender  Age   Income  Illness
0       1  Dallas       1   41  40367.0        0
1       2  Dallas       1   54  45084.0        0
2       3  Dallas       1   42  52483.0        0
3       4  Dallas       1   40  40941.0        0
4       5  Dallas       1   46  50289.0        0

In [148]:
titles=list(dataset.columns)
titles

['Number', 'City', 'Gender', 'Age', 'Income', 'Illness']

In [149]:
titles[0],titles[1]=titles[1],titles[0]
titles

['City', 'Number', 'Gender', 'Age', 'Income', 'Illness']

In [150]:
dataset=dataset[titles]
dataset

City  Number  Gender  Age    Income  Illness
0       Dallas       1       1   41   40367.0        0
1       Dallas       2       1   54   45084.0        0
2       Dallas       3       1   42   52483.0        0
3       Dallas       4       1   40   40941.0        0
4       Dallas       5       1   46   50289.0        0
5       Dallas       6       0   36   50786.0        0
6       Dallas       7       0   32   33155.0        0
7       Dallas       8       1   39   30914.0        0
8       Dallas       9       1   51   68667.0        0
9       Dallas      10       0   30   50082.0        0
10      Dallas      11       0   48   41524.0        1
11      Dallas      12       1   47   54777.0        0
12      Dallas      13       1   46   62749.0        0
13      Dallas      14       0   42   50894.0        0
14      Dallas      15       0   61   38429.0        0
15      Dallas      16       1   43   34074.0        0
16      Dallas      17       1   27   50398.0        0
17      Dallas      18       1   38   46373.0        1
18      Dallas      19       1   47   51137.0        0
19      Dallas      20       0   35   23688.0        0
20      Dallas      21       1   57   17378.0        0
21      Dallas      22       1   33   45919.0        0
22      Dallas      23       0   33   23001.0        0
23      Dallas      24       0   27   34292.0        1
24      Dallas      25       1   58   55190.0        0
25      Dallas      26       1   64   26169.0        0
26      Dallas      27       1   58   57322.0        0
27      Dallas      28       1   44   61704.0        0
28      Dallas      29       1   34   53619.0        0
29      Dallas      30       1   45   47421.0        1
...        ...     ...     ...  ...       ...      ...
149970  Austin  149971       0   63   99950.0        0
149971  Austin  149972       0   30   76928.0        0
149972  Austin  149973       1   46   84395.0        0
149973  Austin  149974       0   52   77272.0        0
149974  Austin  149975       0   39   90430.0        0
149975  Austin  149976       0   51   92132.0        0
149976  Austin  149977       1   49   91519.0        0
149977  Austin  149978       1   51  107123.0        0
149978  Austin  149979       1   58  100949.0        0
149979  Austin  149980       1   43   86737.0        0
149980  Austin  149981       0   53   89384.0        1
149981  Austin  149982       1   50   77134.0        0
149982  Austin  149983       0   47   92157.0        0
149983  Austin  149984       0   25   92482.0        0
149984  Austin  149985       1   51   99075.0        0
149985  Austin  149986       0   25   74947.0        0
149986  Austin  149987       0   63   80381.0        0
149987  Austin  149988       0   55   62501.0        0
149988  Austin  149989       0   26   77823.0        0
149989  Austin  149990       1   52   83688.0        0
149990  Austin  149991       0   26   82163.0        0
149991  Austin  149992       1   51   97510.0        0
149992  Austin  149993       1   37   88408.0        0
149993  Austin  149994       1   64   89906.0        0
149994  Austin  149995       0   37  106097.0        0
149995  Austin  149996       1   48   93669.0        0
149996  Austin  149997       1   25   96748.0        0
149997  Austin  149998       1   26  111885.0        0
149998  Austin  149999       1   25  111878.0        0
149999  Austin  150000       0   37   87251.0        0

[150000 rows x 6 columns]

In [151]:
dataset.isnull().any()

City       False
Number     False
Gender     False
Age        False
Income     False
Illness    False
dtype: bool

In [152]:
dataset['City'].unique()

array(['Dallas', 'New York City', 'Los Angeles', 'Mountain View',
       'Boston', 'Washington D.C.', 'San Diego', 'Austin'], dtype=object)

In [153]:
x=dataset.iloc[:,1:6].values
y=dataset.iloc[:,0:1].values

In [154]:
y

array([['Dallas'],
       ['Dallas'],
       ['Dallas'],
       ...,
       ['Austin'],
       ['Austin'],
       ['Austin']], dtype=object)

In [155]:
y.ndim

2

In [156]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [157]:
y

array([[0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 1.0, ..., 0.0, 0.0, 0.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [158]:
y.shape

(150000, 8)

In [159]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [160]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [161]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [162]:
cat=Sequential()

In [163]:
cat.add(Dense(5,kernel_initializer="random_uniform",activation="relu"))

In [164]:
cat.add(Dense(10,kernel_initializer="random_uniform",activation="relu"))

In [165]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="softmax"))

In [166]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [167]:
cat.fit(x_train,y_train,batch_size=32,epochs=15)

Epoch 1/15
120000/120000 [==============================] - 5s 42us/sample - loss: 0.6395 - acc: 0.7658
Epoch 2/15
120000/120000 [==============================] - 4s 35us/sample - loss: 0.1183 - acc: 0.9695
Epoch 3/15
120000/120000 [==============================] - 4s 37us/sample - loss: 0.0623 - acc: 0.9827
Epoch 4/15
120000/120000 [==============================] - 4s 35us/sample - loss: 0.0445 - acc: 0.9874
Epoch 5/15
120000/120000 [==============================] - 4s 35us/sample - loss: 0.0364 - acc: 0.9897
Epoch 6/15
120000/120000 [==============================] - 4s 36us/sample - loss: 0.0315 - acc: 0.9908
Epoch 7/15
120000/120000 [==============================] - 4s 36us/sample - loss: 0.0278 - acc: 0.9920
Epoch 8/15
120000/120000 [==============================] - 4s 36us/sample - loss: 0.0250 - acc: 0.9928
Epoch 9/15
120000/120000 [==============================] - 4s 35us/sample - loss: 0.0230 - acc: 0.9934
Epoch 10/15
120000/120000 [==============================] - 4s 

In [168]:
x_train.shape

(120000, 5)

In [169]:
y_train.shape

(120000, 8)

In [170]:
ypred=cat.predict(x_test)

In [171]:
ypred

array([[0.0000000e+00, 0.0000000e+00, 9.9999261e-01, ..., 7.4148429e-06,
        0.0000000e+00, 0.0000000e+00],
       [9.9853015e-01, 2.3928266e-13, 1.2817246e-34, ..., 1.1224440e-19,
        1.4698053e-03, 7.8241982e-09],
       [0.0000000e+00, 6.7187362e-24, 9.3077209e-29, ..., 2.5906138e-06,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [2.1891978e-04, 1.1402257e-07, 1.9529516e-31, ..., 2.9170705e-15,
        9.9950838e-01, 2.6081927e-04],
       [0.0000000e+00, 2.6012748e-07, 3.8125052e-32, ..., 1.6000531e-07,
        1.1885061e-34, 9.3563367e-37],
       [0.0000000e+00, 0.0000000e+00, 2.1253203e-13, ..., 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [172]:
dataset.head()

City  Number  Gender  Age   Income  Illness
0  Dallas       1       1   41  40367.0        0
1  Dallas       2       1   54  45084.0        0
2  Dallas       3       1   42  52483.0        0
3  Dallas       4       1   40  40941.0        0
4  Dallas       5       1   46  50289.0        0

In [173]:
cat.predict_classes(sc.transform([[7,1,24,75898,0]]))

array([2], dtype=int64)